# Generated by Django 4.0 on 2021-12-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='VOCPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=20)),
                ('source_database', models.CharField(max_length=20)),
                ('pic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
            ],
        ),
        migrations.CreateModel(
            name='COCOPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
            ],
        ),
    ]
