# Generated by Django 4.0 on 2021-12-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_picture_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='filename',
            field=models.CharField(default='filename', max_length=60),
        ),
        migrations.AlterField(
            model_name='vocpicture',
            name='filename',
            field=models.CharField(max_length=60),
        ),
    ]
