# Generated by Django 3.2.3 on 2021-12-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_alter_picture_filename_alter_vocpicture_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocpicture',
            name='pic',
        ),
        migrations.DeleteModel(
            name='COCOPicture',
        ),
        migrations.DeleteModel(
            name='VOCPicture',
        ),
    ]
