# Generated by Django 4.0 on 2021-12-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20211227_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='VOCPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.FileField(upload_to='VOC')),
                ('pic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
            ],
        ),
        migrations.CreateModel(
            name='COCOPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.FileField(upload_to='COCO')),
                ('pic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
            ],
        ),
    ]
