# Generated by Django 4.0 on 2021-12-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_vocpicture_cocopicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COCOPicture',
        ),
    ]
