# Generated by Django 4.0 on 2021-12-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('V', 'VOC format dataset'), ('C', 'COCO format dataset')], default='V', max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('complete_time', models.DateTimeField()),
                ('state', models.CharField(choices=[('W', 'Task is waitng to be taken'), ('P', 'Tasking is pending'), ('D', 'Task is done')], default='W', max_length=1)),
                ('creat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creat_user', to='auth.user')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset')),
                ('take_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_user', to='auth.user')),
            ],
        ),
    ]
